FROM mysql:5.7
EXPOSE 3306
ENV  MYSQL_ROOT_PASSWORD=root
ENV MYSQL_USER=mounir
ENV MYSQL_PASSWORD=n1m2i372
ENV MYSQL_DATABASE=automation
COPY dumps/1_dump-automation.sql /docker-entrypoint-initdb.d/




